---
repos:
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.3.1
  hooks:
  - id: remove-tabs

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.28.0
  hooks:
  - id: yamllint
    args: [-c=.yamllint]

- repo: https://github.com/thoth-station/adviser.git
  rev: 0669b0ea595e9eb59998efb11a236d3039dacdf8
  hooks:
  - id: validate-prescriptions
    files: prescriptions/
    exclude: prescriptions/_prescription_metadata.yaml
