host: khemenu.thoth-station.ninja
tls_verify: true

runtime_environments: []

managers:
  - name: version
    configuration:
      maintainers:
        - goern
        - fridex
      assignees:
        - sesheta
      labels: [bot]
      changelog_file: false
