apiVersion: thoth-station.ninja/v1
kind: prescription
spec:
  release: 2021.03.18.dev
  units:
    boots: []
    pseudonyms: []
    sieves: []
    steps: []
    strides: []
    wraps: []
  wisdom: null
