units:
  wraps:
  - name: AioesphomeapiFedora34RPMWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      runtime_environments:
        operating_systems:
        - name: fedora
          version: "34"
    match:
      state:
        resolved_dependencies:
        - name: aioesphomeapi
          index_url: https://pypi.org/simple
    run:
      justification:
      - type: INFO
        message: >-
          Package 'aioesphomeapi' is packaged as an RPM in
          Fedora 34 as 'python-aioesphomeapi'
        link: https://src.fedoraproject.org/rpms/xrootd
        package_name: aioesphomeapi
