units:
  wraps:
  - name: AioesphomeapiFedora35RPMWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      runtime_environments:
        operating_systems:
        - name: fedora
          version: "35"
    match:
      state:
        resolved_dependencies:
        - name: aioesphomeapi
          index_url: https://pypi.org/simple
    run:
      justification:
      - type: INFO
        message: Package 'aioesphomeapi' is packaged as an RPM in Fedora 35 as 'python3-aioesphomeapi'
        link: https://src.fedoraproject.org/rpms/python3-aioesphomeapi
        package_name: aioesphomeapi
