units:
  wraps:
  - name: DockerComposePyPIReleaseWrap
    type: wrap
    should_include:
      adviser_pipeline: true
    match:
      state:
        resolved_dependencies:
        - name: docker-compose
    run:
      justification:
      - type: WARNING
        message: >-
          Package 'docker-compose' has no recent release, last release dates back to 2021-05-10 11:22:11.785931
        link: https://pypi.org/project/docker-compose/#history
        package_name: docker-compose
