units:
  wraps:
  - name: ActiveDockerComposeScoreCardsWrap
    type: wrap
    should_include:
      adviser_pipeline: true
    match:
      state:
        resolved_dependencies:
        - name: docker-compose
    run:
      justification:
      - type: INFO
        message: Project is actively maintained based on Security Scorecards
        link: https://github.com/ossf/scorecard/blob/main/docs/checks.md
        package_name: docker-compose
