units:
  wraps:
  - name: DockerGitHubReleaseNotesWrap
    run:
      release_notes:
      - organization: docker
        package_version:
          index_url: https://pypi.org/simple
          name: docker
        repository: docker-py
    should_include:
      adviser_pipeline: true
    type: wrap.GitHubReleaseNotes
