units:
  wraps:
    - name: PytestDockerComposeGitHubURWrap
      type: wrap
      should_include:
        adviser_pipeline: true
      match:
        - state:
            resolved_dependencies:
              - name: pytest-docker-compose
      run:
        stack_info:
          - type: WARNING
            message: "Package 'pytest-docker-compose' is hosted on GitHub"
            link: "https://github.com/pytest-docker-compose/pytest-docker-compose"
