units:
  wraps:
    - name: AnsibleFedora34RPMWrap
      type: wrap
      should_include:
        adviser_pipeline: true
      match:
        state:
          resolved_dependencies:
            - name: ansible
              index_url: 'https://pypi.org/simple'
      run:
        stack_info:
          - type: INFO
            message: "Package 'ansible' is packaged as an RPM in Fedora 34 as 'ansible'"
            link: https://src.fedoraproject.org/rpms/ansible
