units:
  wraps:
    - name: MoleculeFedora34RPMWrap
      type: wrap
      should_include:
        adviser_pipeline: true
      match:
        state:
          resolved_dependencies:
            - name: molecule
              index_url: 'https://pypi.org/simple'
      run:
        stack_info:
          - type: INFO
            message: "Package 'molecule' is packaged as an RPM in Fedora 34 as 'python3-molecule'"
            link: https://src.fedoraproject.org/rpms/python3-molecule
