units:
  wraps:
  - name: MoleculeFedora35RPMWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      runtime_environments:
        operating_systems:
        - name: fedora
          version: "35"
    match:
      state:
        resolved_dependencies:
        - name: molecule
          index_url: https://pypi.org/simple
    run:
      justification:
      - type: INFO
        message: Package 'molecule' is packaged as an RPM in Fedora 35 as 'python3-molecule'
        link: https://src.fedoraproject.org/rpms/python3-molecule
        package_name: molecule
