units:
  wraps:
  - name: TasksGitHubReleaseNotesWrap
    run:
      release_notes:
      - organization: pb-
        package_version:
          index_url: https://pypi.org/simple
          name: tasks
        repository: tasks
        tag_version_prefix: v
    should_include:
      adviser_pipeline: true
    type: wrap.GitHubReleaseNotes
