units:
  wraps:
  - name: TasksGitHubReleaseNotesWrap
    type: wrap.GHReleaseNotes
    should_include:
      adviser_pipeline: true
    match:
      state:
        resolved_dependencies:
        - name: tasks
    run:
      release_notes:
        organization: pb-
        repository: tasks
        tag_version_prefix: v
    metadata:
      prescriptions_repository: git@github.com:thoth-station/prescriptions.git
      prescriptions_version: 0.7.4
