units:
  wraps:
  - name: TasksPyPIReleaseWrap
    type: wrap
    should_include:
      adviser_pipeline: true
    match:
      state:
        resolved_dependencies:
        - name: tasks
    run:
      justification:
      - type: WARNING
        message: >-
          Package 'tasks' has no recent release, last release dates back to 2021-05-18 19:30:02.394641
        link: https://pypi.org/project/tasks/#history
        package_name: tasks
