units:
  wraps:
  - name: PrometheusFlaskExporterGitHubReleaseNotesWrap
    run:
      release_notes:
      - organization: rycus86
        package_version:
          index_url: https://pypi.org/simple
          name: prometheus-flask-exporter
        repository: prometheus_flask_exporter
    should_include:
      adviser_pipeline: true
    type: wrap.GitHubReleaseNotes
