units:
  wraps:
    - name: PrometheusClientGitHubURLWrap
      type: wrap
      should_include:
        adviser_pipeline: true
      match:
        - state:
            resolved_dependencies:
              - name: prometheus-client
      run:
        stack_info:
          - type: INFO
            message: "Package 'prometheus-client' is hosted on GitHub"
            link: "https://github.com/prometheus/client_python"
