units:
  wraps:
  - name: PrometheusClientGitHubReleaseNotesWrap
    run:
      release_notes:
      - organization: prometheus
        package_version:
          index_url: https://pypi.org/simple
          name: prometheus-client
        repository: client_python
        tag_version_prefix: v
    should_include:
      adviser_pipeline: true
    type: wrap.GitHubReleaseNotes
