units:
  wraps:
  - name: BinaryArtifactsPrometheusClientScoreCardsWrap
    type: wrap
    should_include:
      adviser_pipeline: true
    match:
      state:
        resolved_dependencies:
        - name: prometheus-client
    run:
      justification:
      - type: INFO
        message: Project does not have binary artifacts in the source repository
        link: https://github.com/ossf/scorecard/blob/main/docs/checks.md
        package_name: prometheus-client
