units:
  wraps:
    - name: DockerGitHubURLWrap
      type: wrap
      should_include:
        adviser_pipeline: true
      match:
        - state:
            resolved_dependencies:
              - name: docker
      run:
        justification:
          - type: INFO
            message: "Package 'docker' is hosted on GitHub"
            link: "https://github.com/docker/docker-py"
            package_name: docker
