units:
  wraps:
  - name: DockerGitHubReleaseNotesWrap
    type: wrap.GHReleaseNotes
    should_include:
      adviser_pipeline: true
    match:
      state:
        resolved_dependencies:
          name: docker
    run:
      release_notes:
        organization: docker
        repository: docker-py
