units:
  boots:
  - name: QuaySecurityTimestampInfoBoot
    type: boot
    metadata:
      datetime: "2021-12-14T16:14:34.445017"
    should_include:
      adviser_pipeline: true
      runtime_environments:
        base_images:
          not: [null]
    run:
      stack_info:
      - type: INFO
        message: >-
          Using security information for predictable stacks based on Quay
          scanners for quay.io/organization/thoth-station as of '2021-12-14T16:14:34.445017'
        link: https://www.projectquay.io/
