units:
  wraps:
    - name: KubernetesFedora34RPMWrap
      type: wrap
      should_include:
        adviser_pipeline: true
        runtime_environments:
          operating_systems:
            - name: fedora
              version: "34"
      match:
        state:
          resolved_dependencies:
            - name: kubernetes
              index_url: 'https://pypi.org/simple'
      run:
        justification:
          - type: INFO
            message: "Package 'kubernetes' is packaged as an RPM in Fedora 34 as 'python-kubernetes'"
            link: https://src.fedoraproject.org/rpms/python-kubernetes
            package_name: kubernetes
