units:
  wraps:
    - name: KubernetesGitHubURLWrap
      type: wrap
      should_include:
        adviser_pipeline: true
      match:
        - state:
            resolved_dependencies:
              - name: kubernetes
      run:
        stack_info:
          - type: INFO
            message: "Package 'kubernetes' is hosted on GitHub"
            link: "https://github.com/kubernetes-client/python"
