units:
  wraps:
  - name: KubernetesGitHubReleaseNotesWrap
    type: wrap.GHReleaseNotes
    should_include:
      adviser_pipeline: true
    match:
      state:
        resolved_dependencies:
        - name: kubernetes
    run:
      release_notes:
        organization: kubernetes-client
        repository: python
        tag_version_prefix: v
