units:
  wraps:
  - name: KubernetesGitHubReleaseNotesWrap
    run:
      release_notes:
      - organization: kubernetes-client
        package_version:
          index_url: https://pypi.org/simple
          name: kubernetes
        repository: python
        tag_version_prefix: v
    should_include:
      adviser_pipeline: true
    type: wrap.GitHubReleaseNotes
